return {
	audio = require('lunaconf.audio'),
	cairo = require('lunaconf.cairo'),
	clients = require('lunaconf.clients'),
	clientswitcher = require('lunaconf.clientswitcher'),
	config = require('lunaconf.config'),
	dbus = require('lunaconf.dbus'),
	dialogs = require('lunaconf.dialogs'),
	displayswitcher = require('lunaconf.displayswitcher'),
	dpi = require('lunaconf.dpi'),
	icons = require('lunaconf.icons'),
	keys = require('lunaconf.keys'),
	launcher = require('lunaconf.launcher'),
	layouts = require('lunaconf.layouts'),
	log = require('lunaconf.log'),
	notify = require('lunaconf.notify'),
	pacman = require('lunaconf.pacman'),
	screens = require('lunaconf.screens'),
	strings = require('lunaconf.strings'),
	theme = require('lunaconf.theme'),
	widgets = require('lunaconf.widgets'),
	utils = require('lunaconf.utils'),
	xdg = require('lunaconf.xdg')
}
