return {
	audio = require('lunaconf.audio'),
	cairo = require('lunaconf.cairo'),
	clients = require('lunaconf.clients'),
	config = require('lunaconf.config'),
	dpi = require('lunaconf.dpi'),
	icons = require('lunaconf.icons'),
	infolay = require('lunaconf.infolay'),
	inifile = require('lunaconf.inifile'),
	keys = require('lunaconf.keys'),
	launcher = require('lunaconf.launcher'),
	layouts = require('lunaconf.layouts'),
	log = require('lunaconf.log'),
	notify = require('lunaconf.notify'),
	screens = require('lunaconf.screens'),
	strings = require('lunaconf.strings'),
	tags = require('lunaconf.tags'),
	theme = require('lunaconf.theme'),
	widgets = require('lunaconf.widgets'),
	utils = require('lunaconf.utils'),
	xdg = require('lunaconf.xdg')
}
