return {
	cairo = require('lunaconf.cairo'),
	clients = require('lunaconf.clients'),
	config = require('lunaconf.config'),
	dbus = require('lunaconf.dbus'),
	dialogs = require('lunaconf.dialogs'),
	displayswitcher = require('lunaconf.displayswitcher'),
	dpi = require('lunaconf.dpi'),
	icons = require('lunaconf.icons'),
	keys = require('lunaconf.keys'),
	layouts = require('lunaconf.layouts'),
	log = require('lunaconf.log'),
	notify = require('lunaconf.notify'),
	screens = require('lunaconf.screens'),
	sidebar = require('lunaconf.sidebar'),
	strings = require('lunaconf.strings'),
	tags = require('lunaconf.tags'),
	theme = require('lunaconf.theme'),
	widgets = require('lunaconf.widgets'),
	utils = require('lunaconf.utils'),
	xdg = require('lunaconf.xdg')
}
